### ISSUE TITLE
Which part of the model needs to be modified to achieve the effect you show?

### ISSUE THREAD

**Issue by Alex-fishred** [Bin-ze/BEVFormer_segmentation_detection#12]
深入了解後，由衷地佩服您的研究
方便簡略地說明你是修改了哪些地方才實現這樣的效果嗎?
例如模型的head、下游seg是如何實現的等等??

再次謝謝您偉大的研究!

**Comment by Bin-ze** [comment]
我的实现其实遵循较为简单的宗旨，借助BEVFORMER算法得到的BEV特征，通过分割解码器来完成分割任务
具体思路可以简述如下：
![image](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/72087870/5f788a26-a75f-4abc-93b8-e578495fde6d)
这只是算法上的实现，除此之外，为了不更改原始实现的可用性，需要做大量的努力，这涉及对mmdet3d的理解，比如runner，hook，register等等。还需要设计分割损失，设计dataloder从nuscene中读取分割标注用于loss回传，设计新的推理逻辑来可视化分割结果等等。希望我的回复可以帮助你

**Comment by Alex-fishred** [comment]
謝謝你的回覆
透過decoder 來實現分割這部分我理解，如同論文上面說的可以直接沿用BEV特徵實現，但你說的還要設計分割loss 是什麼意思？（你是指我想用單鏡頭重新訓練來回覆嗎？），因為採用單鏡頭的想法我已放棄實現

**Comment by Bin-ze** [comment]
設計分割loss的意思仅仅是对分割分支进行监督而已

**Comment by Alex-fishred** [comment]
不好意思 作為BEV與深度學習新手 我正在嘗試釐清所以過程
根據你的回答，我的認知為
雖然論文本身是說模型輸出的BEV特徵可以直接與下游任務作銜接
但使用者必須事先設計好分割decoder(含loss)，然後重新訓練這個模型
這樣的理解正確嗎? 如同你主頁提供的你訓練好的模型，而不是直接採用原著所提供的模型做分割任務

**Comment by Bin-ze** [comment]
是的，开源的BEVfomer没有实现分割部分的代码，我这里根据自己的理解实现了它
