### ISSUE TITLE
请问seg_subnet.py、seg_sugnet.py、seg_sunet.pyz中的哪个segEncode被使用了？

### ISSUE THREAD

**Issue by admyxs** [Bin-ze/BEVFormer_segmentation_detection#15]
请问seg_subnet.py、seg_sugnet.py、seg_sunet.pyz中的哪个segEncode被使用了？
三个文件里面都有SegEncode，配置的时候到底用的哪一个呢？

**Comment by admyxs** [comment]
已经点过star了，大佬能不能回答一下

**Comment by admyxs** [comment]
我看了__init__里面好像是seg_sebnet.py，是这样吗？
`
from .seg_subnet import SegEncode, DeconvEncode, SegEncode_v1
`

**Comment by Bin-ze** [comment]
> 我看了__init__里面好像是seg_sebnet.py，是这样吗？ `from .seg_subnet import SegEncode, DeconvEncode, SegEncode_v1`

是的，分割网络的实现在seg_subnet中，网络图：https://private-user-images.githubusercontent.com/72087870/285648526-5f788a26-a75f-4abc-93b8-e578495fde6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzU1NjgsIm5iZiI6MTcwNDA3NTI2OCwicGF0aCI6Ii83MjA4Nzg3MC8yODU2NDg1MjYtNWY3ODhhMjYtYTc1Zi00YWJjLTkzYjgtZTU3ODQ5NWZkZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDAyMTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Nzk1MzNkYWQ0Njc0N2NiNDdjYjMzZmQ4MTk5MjYzYzE0NGIzNDBmOGYxNWRlZjNiMmQ0NzdhNjAxYTk1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vamON9SQ4E8AVAnQYCQY1b999NwhRXKlq9MTkkXIsGo
