### ISSUE TITLE
请问torchmetrics和torch的安装顺序是什么？

### ISSUE THREAD

**Issue by admyxs** [Bin-ze/BEVFormer_segmentation_detection#16]
我在原来bevformer的环境直接安装torchmetrics，发现出错了,
而且安装torchmetrics会安装torch2.1.0版本，与bevformer的torch版本不符，请问这个是如何解决的，万般感谢！！！
![image](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/50825926/6c773125-a70b-4193-bbca-eb8806dd86a6)

**Comment by Bin-ze** [comment]
你使用pip安装一下试试，我之前安装的时候应该没有顺序的问题

**Comment by admyxs** [comment]
谢谢，这个我没有解决，不过我仔细看了看，引入torchmetrics这个包主要是用于计算IoU等数据，我这里直接替换了计算IoU的代码

**Comment by Bin-ze** [comment]
> 谢谢，这个我没有解决，不过我仔细看了看，引入torchmetrics这个包主要是用于计算IoU等数据，我这里直接替换了计算IoU的代码

是的，这个包是我拿来计算IOU指标的，可以使用其他包来替代的
