### ISSUE TITLE
请问哪里是用来设置分割的类别的？

### ISSUE THREAD

**Issue by admyxs** [Bin-ze/BEVFormer_segmentation_detection#17]
你好，感谢您出色的工作
我这里似乎找到了设置分割的类别信息，但不是特别清楚，是这里吗？
`
class VectorizedLocalMap(object):
    def __init__(self,
                 dataroot,
                 patch_size,
                 canvas_size,
                 line_classes=['road_divider', 'lane_divider'],
                 ped_crossing_classes=['ped_crossing'],
                 contour_classes=['road_segment', 'lane'],
                 sample_dist=1,
                 num_samples=250,
                 padding=False,
                 normalize=False,
                 fixed_num=-1,
                 class2label={
                     'road_divider': 0,
                     'lane_divider': 0,
                     'ped_crossing': 1,
                     'contours': 2,
                     'others': -1,
                 }):
`
但我对这里的类别不是特别清楚，您能解答一下吗，

1、类别中说的是4类，是不是others算是一类呢？
2、这里是不是把['road_divider', 'lane_divider']两个类算作一个类line_classes了呢？
`
line_classes=['road_divider', 'lane_divider'],
ped_crossing_classes=['ped_crossing'],
contour_classes=['road_segment', 'lane'],
`
3、如果我要是想把11类都预测，是不是需要在函数命名里面全部写上呢？

万分感谢！！！

**Comment by Bin-ze** [comment]
1. 是的，other算一类
2. 是的
3. 把11都预测，应该需要稍微修改一下逻辑，我虽然没有使用，但是实现了lss格式的分割标签读取方法（参考lss），你可以查看他们并修改

**Comment by Bin-ze** [comment]
如果有问题可以再次打开
