### ISSUE TITLE
为什么使用这个网络，使用tiny，自己训练的分割效果不好

### ISSUE THREAD

**Issue by admyxs** [Bin-ze/BEVFormer_segmentation_detection#19]
1、我使用您的分割网络，在tiny模型上使用，发现对于lane的效果很差，lane几乎无法检测，请问这个什么原因呢？

2、而且我这里发现一个问题，网络在第12个epoch训练之后的评估效果，与24个epoch之后的效果差不多几乎没有提升，是不是说明网络过于简单，需要提高复杂性，请问有没有比较好的方向呢？

感谢回答，再次感谢！！！

**Comment by Bin-ze** [comment]
我认为分割图的容量是足够的，因为前面的backbone已经足够重。我没有尝试使用tiny配置训练BEV分割，因此很难确定是否因为网络容量的原因导致的结果变差，你可以提供更详细的日志，否则我不足以帮你分析问题的原因
