### ISSUE TITLE
Visualization of results

### ISSUE THREAD

**Issue by zhangkangkai** [Bin-ze/BEVFormer_segmentation_detection#2]
could you provide the code for visualization?

**Comment by Bin-ze** [comment]
you can check : https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/visual_det_seg.py

The generation steps from the **exported result file** to the **final visualization result** are shown here, but please note that when you need to combine the segmentation results, the segmentation visualization results need to be generated in advance from debug_test.py

**Comment by zhangkangkai** [comment]
Thank you very much. I have successfully visualized the results.
