### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MQC1111** [Bin-ze/BEVFormer_segmentation_detection#21]
您的工作成果简直太棒了
您好，可以请教您一个问题吗，我已经执行完debug_test.py并且得到了分割图，但是当我执行visual_det_seg.py文件时发生报错：
(bev) marco@marco-Legion-Y9000P-IAH7H:~/Master/BEVFormer_segmentation_detection-master$ python visual_det_seg.py
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.287 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.0 seconds.
======
Traceback (most recent call last):
  File "visual_det_seg.py", line 530, in <module>
    render_sample_data(sample_token_list[id], pred_data=bevformer_results, out_path=f"/home/marco/Master/BEVFormer_segmentation_detection-master/resulttt/{sample_token_list[id]}", seg_list=seg_list)
IndexError: list index out of range
(bev) marco@marco-Legion-Y9000P-IAH7H:~/Master/BEVFormer_segmentation_detection-master$ python visual_det_seg.py
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.284 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.0 seconds.
======
Traceback (most recent call last):
  File "visual_det_seg.py", line 530, in <module>
    render_sample_data(sample_token_list[id], pred_data=bevformer_results, out_path=f"/home/marco/Master/BEVFormer_segmentation_detection-master/resulttt/{sample_token_list[id]}", seg_list=seg_list)
IndexError: list index out of range
您能帮忙分析一下原因吗，对于您的帮助万分感谢！

**Comment by Bin-ze** [comment]
请检查：
out_path=f"/home/marco/Master/BEVFormer_segmentation_detection-master/resulttt/{sample_token_list[id]}", seg_list=seg_list
这两个路径，检查sample_token_list和seg_list，问题应该出自这里，如果能debug的话应该可以比较简单的找到问题。而且我注意到你用的是v1.0-mini，也可能于此有关

**Comment by MQC1111** [comment]
非常感谢，我已经解决了

**Comment by azxcdewq123** [comment]
> 非常感谢，我已经解决了

您好，我也遇到了相同的问题。能麻烦问下你这边是怎么解决的吗
