### ISSUE TITLE
nuscenes数据集的map-expansion是如何使用的。

### ISSUE THREAD

**Issue by azxcdewq123** [Bin-ze/BEVFormer_segmentation_detection#23]
感谢作者提供的地图分割的扩充代码。我想知道map-expansion的内容是如何作为训练的真值导入进去的，以及我后期也想尝试修改其他的BEV算法实现地图分割工作，所以能麻烦您大概讲解一下这里map数据集如何在训练、测试阶段使用的，还有在哪里修改、如何修改模型、代码实现分割还有3D检测与分割并行多任务的思路。

**Comment by Bin-ze** [comment]
1. 你可以查看hdmapnet或者beverse的实现，我参考了他们的标签读取方法，具体来说，就是读取地图矢量图，并按感知范围进行裁剪，之后将矢量图进行腐蚀等操作转换为分割图。
2. 分割数据集在训练阶段与传统的语义分割没有差异，唯一的区别在于为了对齐BEV特征，我在进行监督时旋转BEV的特征图对齐了分割GT。
3. 多任务并行的思路很简单，只用一起计算损失并用于梯度反传即可实现并行的联合训练。
4. 测试阶段与训练阶段完全相同，唯一的差别在于我是用one_hot编码激活了对应通道，并使用不同颜色对类别染色输出。
我修改了非常多的地方：
    1. 数据读取
    2. 标签生成
    3. 分割网络设计
    5. 重写了bevformer的类以支持多任务以及支持原始的单任务实现
    6. 设计了损失函数用于监督分割任务
    7. 撰写了分割的可视化程序
    8. 撰写了分割指标计算部分代码
