### ISSUE TITLE
dense_heads问题

### ISSUE THREAD

**Issue by smalltoyfox** [Bin-ze/BEVFormer_segmentation_detection#24]
深入了解您的工作，十分敬佩，有一些问题想请教您，您在dense_heads中定义了BEVFormerHead_seg还有一些东西，但是在config文件中似乎并没有使用，这些定义的类和文件是否有作用？

**Comment by smalltoyfox** [comment]
还想问一下您，您在项目中写了许多的loss，最后用于分割的有哪些？如：projects/mmdet3d_plugin/bevformer/dense_heads/loss_utils.py文件中的BinarySegmentationLoss，SegmentationLoss，MotionSegmentationLoss，GaussianFocalLoss，SpatialRegressionLoss等等

**Comment by Bin-ze** [comment]
> 深入了解您的工作，十分敬佩，有一些问题想请教您，您在dense_heads中定义了BEVFormerHead_seg还有一些东西，但是在config文件中似乎并没有使用，这些定义的类和文件是否有作用？

我后续将实现写在BEVFormerHead里，在配置文件中没有引用的类并没有用到

**Comment by Bin-ze** [comment]
> 还想问一下您，您在项目中写了许多的loss，最后用于分割的有哪些？如：projects/mmdet3d_plugin/bevformer/dense_heads/loss_utils.py文件中的BinarySegmentationLoss，SegmentationLoss，MotionSegmentationLoss，GaussianFocalLoss，SpatialRegressionLoss等等

我使用的分割损失写在配置文件中，其他损失你也可以通过修改配置文件调用

**Comment by smalltoyfox** [comment]
好的，十分感谢您的解惑
