### ISSUE TITLE
visualization understanding

### ISSUE THREAD

**Issue by Deltaidiots** [Bin-ze/BEVFormer_segmentation_detection#27]
First of all great work!
Now based on the video shown in repo, I can see there are lanes as well. Did the segmentation code outputs driveable area with lane segments as well? 
have you compared the results with the original paper and did they match ? 
Thanks

**Comment by Bin-ze** [comment]
I tried an implementation outside of the paper, so I didn't compare with the paper.
But I compared the accuracy of hdmapnet. 
The segmentation annotation of my experiment is the same as hdmapnet, but different from what bevformer mentioned.
