### ISSUE TITLE
关于代码debug的问题

### ISSUE THREAD

**Issue by azxcdewq123** [Bin-ze/BEVFormer_segmentation_detection#28]
您好，我想更加深入的了解一下这套代码。但是在尝试debug的时候（从train.py的主函数出发）发现走到读取config文件（即config/bevformer_small.py之类的文件）的时候，它里边写的model、backbone之类的都是字符串形式也就无法读入到具体的模块的类里边去，这里应该是mmlab框架的一些机制导致的，但我对这方面确实了解很少。所以能麻烦您讲述一下debug的一些方法和技巧吗（本人非计算机专业出身代码能力可能较弱还请麻烦介绍的详细一些吧）

**Comment by Bin-ze** [comment]
这是基于注册器实现的，其实比较容易理解，如果你能搞懂mmcv的注册机制的话

**Comment by azxcdewq123** [comment]
> 这是基于注册器实现的，其实比较容易理解，如果你能搞懂mmcv的注册机制的话

感谢回答，那请问能否提供一些相关的快速上手资料呢。另外还有一个问题就是修改后的网络在做推理阶段时，算法输入是什么？只需要nuscenes数据集的六张环视图像就可以吗？那么如果后续我想要尝试做实车部署的话是不是设法获取六个相机的内外参以及图像即可呢？

**Comment by Bin-ze** [comment]
直接看mmcv的官方文档就可以，想当详细
