### ISSUE TITLE
Seg task with custom datasets 

### ISSUE THREAD

**Issue by Looottch** [Bin-ze/BEVFormer_segmentation_detection#29]
There's my doubts:
why seg only task use NMSFreeCoder which seems not related to segmentation but detection?

**Comment by Bin-ze** [comment]
The project is long-standing

Please describe the problem location and I will help you find it when I have time

**Comment by Looottch** [comment]
> The project is long-standing
> 
> Please describe the problem location and I will help you find it when I have time

how to arrange data  to make sure dataset loading is temporal, namely how to keep data from function getitem(idx) temporal which load (idx -2 , idx- 1, idx) for example. thank you in advance

**Comment by Looottch** [comment]
> The project is long-standing
> 
> Please describe the problem location and I will help you find it when I have time
https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/8e2a1beee39946f393322a293f127a489b093377/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py#L341C1-L344C44
I found function format_results skip here , then for eval how to get following results. (I mean how to calculate iou metric for semantic segmentation in repo
![image](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/42186852/3046963c-eebb-46b8-9069-b65fb12c409b)
