### ISSUE TITLE
debug时候出现import error问题怎么解决

### ISSUE THREAD

**Issue by azxcdewq123** [Bin-ze/BEVFormer_segmentation_detection#30]
![屏幕截图 2024-06-05 201930](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/103915029/24543b68-fa38-486b-9029-3b83aefb0c98)

**Comment by Bin-ze** [comment]
mmcv版本错误，需要按照项目需要安装对应的版本

**Comment by azxcdewq123** [comment]
> mmcv版本错误，需要按照项目需要安装对应的版本



> mmcv版本错误，需要按照项目需要安装对应的版本

以下是我的环境，
torch==1.10.0+cu113 torchvision==0.11.0+cu113 torchaudio==0.10.0torch==1.10.0+cu113 torchvision==0.11.0+cu113 torchaudio==0.10.0；
mmcv-full==1.4.0 mmdet==2.14.0 mmsegmentation==0.14.1；mmdetection3d==0.17.1
这个环境里我看mmlab的相关依赖都是和项目里的要求对应，并且我能够正常的运行训练和推理，即./tools/dist_train.sh
但是在debug时候会出现上述报错，这个问题您有遇到过吗

**Comment by Bin-ze** [comment]
可以训练的话，debug应该不会出错。你是如何debug的？命令是什么。只是看错误的话是mmcv的问题

**Comment by azxcdewq123** [comment]
> 可以训练的话，debug应该不会出错。你是如何debug的？命令是什么。只是看错误的话是mmcv的问题

我在debug_train.py中首先在传参部分对config和work-dir加入一个default值
然后在主函数处打了断点
在vscode中选择Python调试c程序来debug；然后启动之后就会报这个错误

**Comment by azxcdewq123** [comment]
> 我在debug_train.py中首先在传参部分对config和work-dir加入一个default值 然后在主函数处打了断点 在vscode中选择Python调试c程序来debug；然后启动之后就会报这个错误

补充以下截图
![屏幕截图 2024-06-06 094103](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/103915029/98e6c537-ec98-4b9d-8774-9fab7b68bcd7)


![屏幕截图 2024-06-06 093934](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/103915029/aef03048-0a41-4a38-a059-acf49bcc18c0)

**Comment by Bin-ze** [comment]
vscode debug时激活一下你的环境，否则我想不到为什么训练可以debug不可以，我从未在执行任何python程序时出现debug报依赖错误但是可以正常运行的bug
