### ISSUE TITLE
关于几个bev_size的定义

### ISSUE THREAD

**Issue by azxcdewq123** [Bin-ze/BEVFormer_segmentation_detection#33]
我想请问下，在配置文件中我注意到有几个"size"想知道是什么作用或含义？包括：
bev_size，voxel_size，gird_conf，另外注意到grid_conf还分为了det和map。这几个参数各自代表什么呢，起什么作用。另外为什么map和det的grid不一样呢？这样做有什么目的

**Comment by Bin-ze** [comment]
![image](https://github.com/user-attachments/assets/c6fcb953-7edb-4c09-a1ef-fa647bd8781f)
这里定义的是hdmapnet定义的分割感知范围以及其他3d目标检测算法所定义的检测感知范围，用于在标注中裁剪标签

**Comment by azxcdewq123** [comment]
图中这两个我理解应该代表的map_grid_conf和det_grid_conf吧？这样做的目的是在训练时候截取感知范围内的真值吗？那在做推理阶段的感知范围也会被限制在这样的大小吗？还是说相机能看到的距离内都能感知到呢？
为什么分割范围要小一些呢？能否将分割的感知范围扩大？

另外bev_h_ = 300，bev_w_ = 300；bev_size=(bev_h_, bev_w_)。这里的bev_size是什么作用呢？在不同的config文件中它的大小是不一样的，调整他的作用是什么？还有voxel_size = [0.2, 0.2, 8]这个参数的作用是什么呢？

**Comment by Bin-ze** [comment]
bev_size指的是用多大的特征图来代表的det感知域的大小，其有明确的物理意义。因此，推理阶段的感知范围也会被限制在这样的大小。在不同的config文件中它的大小是不一样的，是因为我使用不同的特征图大小来验证更大的特征图能否带来更好的效果（相当于变相的增加了感知的粒度，之前可能一辆汽车被1x1x256的特征描述，现在增大二倍），voxel_size = [0.2, 0.2, 8]的用途你应该具体查看代码中对其的使用
