### ISSUE TITLE
请问此项目必须要使用完整的nuscenes数据集吗？

### ISSUE THREAD

**Issue by CrazyMustard-404** [Bin-ze/BEVFormer_segmentation_detection#6]
作者您好，感谢你的工作！
我使用nuscenes-mini数据集在运行debug_test.py时出现报错 FileNotFoundError: CustomNuScenesDataset: [Errno 2] No such file or directory: 'data/nuscenes/maps/expansion/boston-seaport.json'

**Comment by Bin-ze** [comment]
你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了

**Comment by CrazyMustard-404** [comment]
感谢您的回答！
请问您用的是哪个版本的数据集呢？我直接用nuscenes 的 Full dataset (v1.0) 这个数据集是否可行呢？

**Comment by Bin-ze** [comment]
查看这里：https://github.com/nutonomy/nuscenes-devkit#map-versions:~:text=map%20versions%20below.-,Map%20versions,-Here%20we%20give

**Comment by handsomeZhuang** [comment]
> 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了

请问一下，model 必须使用https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（345552811@qq.com）吗？我这边没法用网盘,谢谢！

**Comment by CrazyMustard-404** [comment]
> 查看这里：https://github.com/nutonomy/nuscenes-devkit#map-versions:~:text=map%20versions%20below.-,Map%20versions,-Here%20we%20give

感谢回答，问题已解决！

**Comment by CrazyMustard-404** [comment]
> > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> 
> 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！

你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py)
在code主页就可以下载。

**Comment by handsomeZhuang** [comment]
> > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > 
> > 
> > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> 
> 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。

请问一下，哪个预训练模型有车道线分割结果？

**Comment by CrazyMustard-404** [comment]
> > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > 
> > > 
> > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > 
> > 
> > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> 
> 请问一下，哪个预训练模型有车道线分割结果？

![Snipaste_2023-07-25_18-52-15](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/61932303/63c9e068-e1d8-410d-8b19-e1d6c685b721)

**Comment by handsomeZhuang** [comment]
> > > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > > 
> > > > 
> > > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > > 
> > > 
> > > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> > 
> > 
> > 请问一下，哪个预训练模型有车道线分割结果？
> 
> ![Snipaste_2023-07-25_18-52-15](https://user-images.githubusercontent.com/61932303/255878422-63c9e068-e1d8-410d-8b19-e1d6c685b721.png)

我用的是您上图中第二个红框的300x300的模型，但是输出结果是没有车道线的？需要设置什么参数吗？

**Comment by CrazyMustard-404** [comment]
> 
两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。

**Comment by CrazyMustard-404** [comment]
> 

两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。

**Comment by CrazyMustard-404** [comment]
> > > > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > > > 
> > > > > 
> > > > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > > > 
> > > > 
> > > > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> > > 
> > > 
> > > 请问一下，哪个预训练模型有车道线分割结果？
> > 
> > 
> > ![Snipaste_2023-07-25_18-52-15](https://user-images.githubusercontent.com/61932303/255878422-63c9e068-e1d8-410d-8b19-e1d6c685b721.png)
> 
> 我用的是您上图中第二个红框的300x300的模型，但是输出结果是没有车道线的？需要设置什么参数吗？

两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。

**Comment by handsomeZhuang** [comment]
> > > > > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > > > > 
> > > > > > 
> > > > > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > > > > 
> > > > > 
> > > > > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> > > > 
> > > > 
> > > > 请问一下，哪个预训练模型有车道线分割结果？
> > > 
> > > 
> > > ![Snipaste_2023-07-25_18-52-15](https://user-images.githubusercontent.com/61932303/255878422-63c9e068-e1d8-410d-8b19-e1d6c685b721.png)
> > 
> > 
> > 我用的是您上图中第二个红框的300x300的模型，但是输出结果是没有车道线的？需要设置什么参数吗？
> 
> 两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。

我可视化后，是这样的图：
![image](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/139242546/ec639c27-a712-4ef6-9adc-e9b71c4d5fa7)
另外，我看到bevformer_small_seg_det_300x300.py文件里面有10类，class_names = [
    'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier',
    'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone'
]也不包括车道线，麻烦大佬指点一下，感谢！

**Comment by CrazyMustard-404** [comment]
> > > > > > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > > > > > 
> > > > > > > 
> > > > > > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > > > > > 
> > > > > > 
> > > > > > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> > > > > 
> > > > > 
> > > > > 请问一下，哪个预训练模型有车道线分割结果？
> > > > 
> > > > 
> > > > ![Snipaste_2023-07-25_18-52-15](https://user-images.githubusercontent.com/61932303/255878422-63c9e068-e1d8-410d-8b19-e1d6c685b721.png)
> > > 
> > > 
> > > 我用的是您上图中第二个红框的300x300的模型，但是输出结果是没有车道线的？需要设置什么参数吗？
> > 
> > 
> > 两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。
> 
> 我可视化后，是这样的图： ![image](https://user-images.githubusercontent.com/139242546/256076647-ec639c27-a712-4ef6-9adc-e9b71c4d5fa7.png) 另外，我看到bevformer_small_seg_det_300x300.py文件里面有10类，class_names = [ 'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier', 'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone' ]也不包括车道线，麻烦大佬指点一下，感谢！

按照此顺序执行脚本
![image](https://github.com/Bin-ze/BEVFormer_segmentation_detection/assets/61932303/dc6c1e96-2476-4809-9815-5978e7eb36f3)

**Comment by handsomeZhuang** [comment]
> > > > > > > > > 你使用的地图拓展应该版本有问题，找到合适的版本下载应该就没有问题了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 请问一下，model 必须使用[https://github.com/Bin-ze/BEVFormer_segmentation_detection这里面的seg](https://github.com/Bin-ze/BEVFormer_segmentation_detection%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84seg) 模型吗？我用BEVformer的模型报这个错误：TypeError: stat_scores() got an unexpected keyword argument 'reduce'！ 如果必须使用seg模型的话，可以发我邮箱（[345552811@qq.com](mailto:345552811@qq.com)）吗？我这边没法用网盘,谢谢！
> > > > > > > 
> > > > > > > 
> > > > > > > 你好，我使用的权重为[BEVFomer-small-300x300](https://github.com/Bin-ze/BEVFormer_segmentation_detection/blob/master/projects/configs/bevformer/bevformer_small_seg_det_300x300.py) 在code主页就可以下载。
> > > > > > 
> > > > > > 
> > > > > > 请问一下，哪个预训练模型有车道线分割结果？
> > > > > 
> > > > > 
> > > > > ![Snipaste_2023-07-25_18-52-15](https://user-images.githubusercontent.com/61932303/255878422-63c9e068-e1d8-410d-8b19-e1d6c685b721.png)
> > > > 
> > > > 
> > > > 我用的是您上图中第二个红框的300x300的模型，但是输出结果是没有车道线的？需要设置什么参数吗？
> > > 
> > > 
> > > 两个红框是一个权重；至于车道线，按照作者提供的脚本，先推理后再可视化即可分割出车道线。
> > 
> > 
> > 我可视化后，是这样的图： ![image](https://user-images.githubusercontent.com/139242546/256076647-ec639c27-a712-4ef6-9adc-e9b71c4d5fa7.png) 另外，我看到bevformer_small_seg_det_300x300.py文件里面有10类，class_names = [ 'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier', 'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone' ]也不包括车道线，麻烦大佬指点一下，感谢！
> 
> 按照此顺序执行脚本 ![image](https://user-images.githubusercontent.com/61932303/256079342-dc6c1e96-2476-4809-9815-5978e7eb36f3.png)

万分感谢大佬！
这个开源代码docs和README跟代码不匹配，对新人不太友好

**Comment by Bin-ze** [comment]
这是我之前的项目，简单的添加了分割代码，因此实现上可能有不足之处，等有时间我会补全文档

**Comment by handsomeZhuang** [comment]
> 这是我之前的项目，简单的添加了分割代码，因此实现上可能有不足之处，等有时间我会补全文档

 感谢大佬！

**Comment by LadissonLai** [comment]
> 这是我之前的项目，简单的添加了分割代码，因此实现上可能有不足之处，等有时间我会补全文档

期待大佬更新代码文档
