### ISSUE TITLE
FileNotFoundError: img file does not exist: data/nucsenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg  

### ISSUE THREAD

**Issue by aqr1961** [Bin-ze/BEVFormer_segmentation_detection#8]
raise FileNotFoundError(msg_tmpl.format(filename))                                                                                                           │···························································
FileNotFoundError: img file does not exist: data/nucsenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg    
不知道为什么会 出现这样的错误，我已经在config文件中设置nuscenes为我nuscenes数据集的路径，并且在这个数据集中我确实找到了这张图片。

**Comment by Bin-ze** [comment]
试一下绝对路径，问题应该是由于这里的图像路径是相对的，无法通过该路径找到图像导致的发自我的 iPhone在 2023年9月28日，16:36，aqr1961 ***@***.***> 写道：﻿
raise FileNotFoundError(msg_tmpl.format(filename))                                                                                                           │···························································
FileNotFoundError: img file does not exist: data/nucsenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg
不知道为什么会 出现这样的错误，我已经在config文件中设置nuscenes为我nuscenes数据集的路径，并且在这个数据集中我确实找到了这张图片。
